Repository AliUmman/hello-world, pull requests merged in 2019-06, with the labels that each got.

#5 new bug found and solved
  HelloWorld.java
Labels: invalid

#7 initial number is 0
  HelloWorld.java
Labels: help wanted

#11 big number bug proposal
  HelloWorld.java
Labels: bug, invalid
